### ISSUE TITLE
AndroidMessage

### ISSUE THREAD

**Issue by CoalaJoe** [fre5h/FirebaseCloudMessagingBundle#1]
I wanted to ask you why you are sending an AndroidMessage here? 
https://github.com/fre5h/FirebaseCloudMessagingBundle/blob/master/Command/FirebaseSendTestMessageCommand.php#L69
Are AndroidMessages universial?

**Comment by fre5h** [comment]
@CoalaJoe I started to do this bundle in the context of the current project at that moment. But then plans have changed and I haven't finished bundle yet. So now it is still unstable and in dev mode. I am planning to finish all features which I described in README, but not sure exactly when I have a time for it.
So AndroidMessage was temporary solution for that moment. This console command should be configurable and smart in my plans.

**Comment by CoalaJoe** [comment]
@fre5h Thanks for the quick response.

Do you know any alternatives or should I implement the Firebase Cloud Messaging API in my own application?

**Comment by fre5h** [comment]
@CoalaJoe Depends on what do you need.

**Comment by CoalaJoe** [comment]
@fre5h Pushnotifications over FCM.

**Comment by lashae** [comment]
@CoalaJoe It has passed about a year, how could you manage to implement "Pushnotifications over FCM" in PHP?
